//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isler
    {
        public int IsID { get; set; }
        public string IsBaslik { get; set; }
        public string IsAciklama { get; set; }
        public Nullable<int> IsPersonelID { get; set; }
        public Nullable<System.DateTime> IletilenTarih { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> IsDurumID { get; set; }
        public string IsYorum { get; set; }
        public Nullable<bool> IsOkunma { get; set; }
    
        public virtual IsDurumlar IsDurumlar { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
